ARG IMAGE=hello-world:invalid

FROM ${IMAGE}

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates python3 iputils-ping netcat-openbsd curl jq \
    && apt-get -qq -y autoclean \
    && apt-get -qq -y autoremove \
    && apt-get -qq -y clean
