services:
  rest_api:
    image: ${DOCKER_TAG_PREFIX}_core_rest_api:${DEPLOY_VERSION}
    environment:
      - LOGLEVEL=DEBUG
      - DATA_DIR=${DB_DATA_DIRECTORY}
      - LOGS_DIR=${DB_LOGS_DIRECTORY}
      - DEPLOY_VERSION=${DEPLOY_VERSION}
      - DB_ID=${DB_ID}
      - DB_ROUTER=zmq_router
      - DB_ROUTER_FRONTEND_PORT=${DB_ROUTER_FRONTEND_PORT}
      - DB_ROUTER_BACKEND_PORT=${DB_ROUTER_BACKEND_PORT}
      - DB_ROUTER_SUB_PORT=${DB_ROUTER_SUB_PORT}
      - DB_ROUTER_PUB_PORT=${DB_ROUTER_PUB_PORT}
      # separate multiple usernames or passwords with '#'
      - LOGIN_USER_NAMES=databeam
      # generate hashes with: echo -n "p4ssWord" | sha256sum | tr -d "[:space:]-"
      - LOGIN_PASSWORD_HASHES=37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f  # 'default'
    volumes:
      - ${ROOT_DIR}/data:${DB_DATA_DIRECTORY}
      - ${ROOT_DIR}/logs:${DB_LOGS_DIRECTORY}
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${REST_API_PUBLIC_PORT}:5000"
      - "5001:5001"
    networks:
      - internal_nw
      - public_nw
    depends_on:
      controller:
        condition: service_healthy
    restart: unless-stopped
    stop_grace_period: 20s
