services:
  startstop_forwarder:
    image: ${DOCKER_TAG_PREFIX}_system_startstop_forwarder:${DEPLOY_VERSION}
    environment:
      - LOGLEVEL=DEBUG
      - CONFIG_DIR=${DB_CONFIG_DIRECTORY}
      - DATA_DIR=${DB_DATA_DIRECTORY}
      - DEPLOY_VERSION=${DEPLOY_VERSION}
      - DB_ID=${DB_ID}
      - DB_ROUTER=localhost
      - DB_ROUTER_FRONTEND_PORT=${DB_ROUTER_FRONTEND_PORT}
      - DB_ROUTER_BACKEND_PORT=${DB_ROUTER_BACKEND_PORT}
      - DB_ROUTER_SUB_PORT=${DB_ROUTER_SUB_PORT}
      - DB_ROUTER_PUB_PORT=${DB_ROUTER_PUB_PORT}
    volumes:
      - ${ROOT_DIR}/config:${DB_CONFIG_DIRECTORY}
      - ${ROOT_DIR}/data:${DB_DATA_DIRECTORY}
    depends_on:
      controller:
        condition: service_healthy
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 20s
