services:
  system_monitor:
    image: ${DOCKER_TAG_PREFIX}_module_system_monitor:${DEPLOY_VERSION}
    environment:
      - LOGLEVEL=DEBUG
      - CONFIG_DIR=${DB_CONFIG_DIRECTORY}
      - DATA_DIR=${DB_DATA_DIRECTORY}
      - DEPLOY_VERSION=${DEPLOY_VERSION}
      - DB_ID=${DB_ID}
      - DB_ROUTER=zmq_router
      - DB_ROUTER_FRONTEND_PORT=${DB_ROUTER_FRONTEND_PORT}
      - DB_ROUTER_BACKEND_PORT=${DB_ROUTER_BACKEND_PORT}
      - DB_ROUTER_SUB_PORT=${DB_ROUTER_SUB_PORT}
      - DB_ROUTER_PUB_PORT=${DB_ROUTER_PUB_PORT}
    volumes:
      - ${ROOT_DIR}/config:${DB_CONFIG_DIRECTORY}
      - ${ROOT_DIR}/data:${DB_DATA_DIRECTORY}
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /dev/urandom:/dev/random
      - /mnt:/mnt
    depends_on:
      controller:
        condition: service_healthy
    networks:
      - internal_nw
    restart: unless-stopped
